In [1]:
import numpy as np
from function import get_colors,Ternary_to_Decimal,Decimal_to_Ternary
from tqdm import tqdm

words = np.load("data_sourse/npy/words.npy",allow_pickle=True)
words_v2 = np.load("data_sourse/npy/words_for_version2.npy",allow_pickle=True)
wordle_words = np.load("data_sourse/npy/wordle_words.npy",allow_pickle=True)

a = np.load("data_sourse/npy/first_cal_entropy-old.npy",allow_pickle=True)
b = np.load("data_sourse/npy/first_cal_entropy-new.npy",allow_pickle=True)


In [2]:
a

array([['abase', '-21.4301656', '4.035330652', '4.035331005', 'True'],
       ['abate', '-16.6544008', '4.252027765', '4.252037459', 'True'],
       ['abbey', '-11.5860314', '3.447259201', '3.447584480', 'True'],
       ...,
       ['zebra', '-14.3064911', '3.996753361', '3.996802714', 'True'],
       ['zesty', '-18.5704114', '3.709570672', '3.709573240', 'True'],
       ['zonal', '-15.5587056', '4.156567214', '4.156587932', 'True']],
      dtype='<U11')

In [3]:
b

array([['aback', '-18.2073114', '3.155813158', '0', 'True'],
       ['abase', '-21.4301729', '4.287880734', '0', 'True'],
       ['abate', '-16.6544056', '4.554759367', '0', 'True'],
       ...,
       ['zebra', '-14.3064968', '4.027418692', '0', 'True'],
       ['zesty', '-18.5704187', '3.756139560', '0', 'True'],
       ['zonal', '-15.5587088', '4.198428780', '0', 'True']], dtype='<U11')

In [2]:
words

array([['aback', '-20.1354521', '-17.4105207', '-18.2073114'],
       ['abase', '-23.4084706', '-20.6259452', '-21.4301729'],
       ['abate', '-16.6850941', '-16.6243565', '-16.6544056'],
       ...,
       ['zebra', '-14.6965169', '-13.9997901', '-14.3064968'],
       ['zesty', '-20.4084706', '-17.7877579', '-18.5704187'],
       ['zonal', '-15.0175851', '-16.4346599', '-15.5587088']],
      dtype='<U11')

In [3]:
words_v2

array([['aback', '-18.2073114', '0', '0', 'True'],
       ['abase', '-21.4301729', '0', '0', 'True'],
       ['abate', '-16.6544056', '0', '0', 'True'],
       ...,
       ['zebra', '-14.3064968', '0', '0', 'True'],
       ['zesty', '-18.5704187', '0', '0', 'True'],
       ['zonal', '-15.5587088', '0', '0', 'True']], dtype='<U11')

In [4]:
wordle_words

array([['aback'],
       ['abase'],
       ['abate'],
       ...,
       ['zebra'],
       ['zesty'],
       ['zonal']], dtype=object)

In [7]:
a

array([['aback', '-18.2073114', '3.155813158', '0', 'True'],
       ['abase', '-21.4301729', '4.287880734', '0', 'True'],
       ['abate', '-16.6544056', '4.554759367', '0', 'True'],
       ...,
       ['zebra', '-14.3064968', '4.027418692', '0', 'True'],
       ['zesty', '-18.5704187', '3.756139560', '0', 'True'],
       ['zonal', '-15.5587088', '4.198428780', '0', 'True']], dtype='<U11')

In [4]:
len(words)

2310

In [2]:
Ternary_to_Decimal(get_colors(words[0][0],words[2][0]))

190

In [3]:
words[0][0]

'abase'

In [4]:
words[2][0]

'abbey'

In [ ]:
all_colors = np.zeros((length,length)).astype('i4')
for i in tqdm(range(length)):
    for j in np.arange(length):
        all_colors[i][j] = Ternary_to_Decimal(get_colors(words[i][0],words[j][0]))
np.save('data_sourse/npy/all_colors.npy',all_colors)

In [5]:
Decimal_to_Ternary(190)

array([2, 1, 0, 0, 1])

In [6]:
get_colors("abase","abbey")

array([2, 1, 0, 0, 1])

In [14]:
import pdb
import numpy as np
def get_colors(word,answer):
    colors = np.zeros(5).astype('i4')
    used = np.zeros(5).astype('i4')
    for i in np.arange(5):
        if(word[i] == answer[i]):
            colors[i] = 2
            used[i] = 1
    for i in np.arange(5):
        if(colors[i] == 2):
            continue
        letter = word[i]
        for j in np.arange(5):
            if(letter == answer[j] and used[j] == 0):
                colors[i] = 1
                used[j] = 1
                break
    return colors

In [15]:
get_colors("abase","banal")

array([1, 1, 1, 0, 0])

In [10]:
words[1][0]

'abase'

In [16]:
words[165][0]

'beach'